/**
 * Read SVG files from public/symbols/ and generate src/lib/patterns/builtin-icons.ts
 * with base64-encoded SVG data URIs.
 * Run: npx tsx scripts/generate-builtin-icons.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const SYMBOLS_DIR = join(process.cwd(), "public", "symbols");
const OUT_FILE = join(process.cwd(), "src", "lib", "patterns", "builtin-icons.ts");

const ids = [
  "knit",
  "purl",
  "yarn-over",
  "purl-in-yarn-over",
  "cross-purl",
  "cross-knit",
  "k2tog-left",
  "k2tog-right",
  "p2tog-left",
  "p2tog-right",
  "k3tog",
  "p3tog",
  "slip-back",
  "slip-front",
  "two-from-one",
  "three-from-one",
  "four-from-one",
  "four-together",
  "five-from-one",
  "five-together",
  "five-knit",
  "wrap",
  "bobble",
  "empty"
];

const entries: string[] = [];

for (const id of ids) {
  const buf = readFileSync(join(SYMBOLS_DIR, `${id}.svg`));
  const b64 = buf.toString("base64");
  entries.push(`  "${id}": "data:image/svg+xml;base64,${b64}"`);
}

const content = `// Auto-generated by scripts/generate-builtin-icons.ts
// Do not edit manually. Run: npx tsx scripts/generate-builtin-icons.ts

export const BUILTIN_ICONS: Record<string, string> = {
${entries.join(",\n")}
};
`;

writeFileSync(OUT_FILE, content, "utf-8");
console.log(`Generated ${OUT_FILE} with ${ids.length} icons.`);
